data:
  duration: 0.3483 # Audio duration during training, must be less than the duration of the shortest audio clip
  train_path: 'yx2/train' # Create a folder named "audio" under this path and put the audio clip in it
  valid_path: 'yx2/val' # Create a folder named "audio" under this path and put the audio clip in it
  extensions: # List of extension included in the data collection
    - wav
mel:
  type: 'stft' # use "none" or "default" to use default
  sr: 16000
  num_mels: 512 # if stft need to match others
  n_fft: 1024
  win_size: 1024
  hop_size: 160
  fmin: 0
  fmax: 8000
model:
  type: 'CFNaiveMelPE'
  out_dims: 360
  hidden_dims: 512
  n_layers: 6
  n_heads: 8
  f0_min: 32.70
  f0_max: 1975.5
  use_fa_norm: true
  conv_only: true
  conv_dropout: 0.0
  atten_dropout: 0.0
  use_harmonic_emb: false
loss:
  loss_scale: 10
device: cuda
env:
  expdir: exp/yx2_001ac_stft
  gpu_id: 0
train:
  aug_add_music: true
  aug_keyshift: true
  f0_shift_mode: 'keyshift'
  keyshift_min: -6
  keyshift_max: 6
  aug_noise: true
  noise_ratio: 0.7
  brown_noise_ratio: 1
  aug_mask: true
  aug_mask_v_o: true
  aug_mask_vertical_factor: 0.05
  aug_mask_vertical_factor_v_o: 0.3
  aug_mask_iszeropad_mode: 'noise' # randon zero or noise
  aug_mask_block_num: 1
  aug_mask_block_num_v_o: 1
  num_workers: 14 # If your cpu and gpu are both very strong, set to 0 may be faster!
  amp_dtype: fp32 # only can ues fp32, else nan
  batch_size: 128
  use_redis: true
  cache_all_data: true # Save Internal-Memory or Graphics-Memory if it is false, but may be slow
  cache_device: 'cpu' # Set to 'cuda' to cache the data into the Graphics-Memory, fastest speed for strong gpu
  epochs: 100000
  interval_log: 100
  interval_val: 5000
  interval_force_save: 5000
  lr: 0.0005
  decay_step: 100000
  gamma: 0.7071
  weight_decay: 0.0001
  save_opt: false
